name = "miamipool"
type = "javascript"
zone_id = ""
account_id = "c60e829b3831ea5b11b2398ef68bda23"
route = "api.mine.miami/*"
workers_dev = true

kv_namespaces = [
  { binding = "KV", id = "fb2055c6ae394545969d6bf7146a70d1", preview_id = "fb2055c6ae394545969d6bf7146a70d1" },
]

[build]
command = "yarn && yarn format && yarn build"
[build.upload]
format = "service-worker"

[triggers]
crons = ["*/5 * * * *", "*/2 * * * *"]